POST http://localhost:8000/api/pq-submit/
Content-Type: application/json

[
    {
        "question_id": 2,
        "option_id": 3
    },
    {
        "question_id": 2,
        "option_id": 3
    }
]
