# Generated by Django 4.1.2 on 2024-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalityoption",
            name="option_res",
            field=models.CharField(default="dummy_text", max_length=500),
            preserve_default=False,
        ),
    ]
