# Generated by Django 4.1.2 on 2024-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_personalityoption_option_res"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ability_tag", models.CharField(max_length=32)),
                ("ability_text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Abilities",
            },
        ),
    ]
